title: Rohit Menon
logo: assets/rohit_picture.png
description: Graduate from UC Berkeley with a Masters in Information and Data Science  Graduate from UW-Madison with Bachelors in Data Science and a minor in Computer Science
theme: jekyll-theme-minimal

# Navigation Links
nav_links:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Resume"
    url: "/resume/"
  - title: "Projects"
    url: "/projects/"
  - title: "Contact"
    url: "/contact/"
